version: '3.8'
services:
  backend: 
    build: 
      context: ./server
      dockerfile: Dockerfile
    env_file:
      - ./server/.env
    container_name: backend 
    ports:
      - "3001:3001"

  client:
    build: 
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - ./client/.env
    container_name: client
    ports:
      - "4200:80"
    depends_on:
      - backend