export const SET_PROVINCE = 'SET_PROVINCE'
export const SET_DISTRICT = 'SET_DISTRICT'
export const SET_TOWN = 'SET_TOWN'
export const SET_USER = 'SET_USER'
export const DROP_USER = 'DROP_USER'
export const SET_MULTI = 'SET_MULTI'
export const DROP_MULTI = 'DROP_MULTI'